-- TABLA DE LAS RUTAS
CREATE TABLE RUTA (
    ID_RUTA INTEGER PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    COLOR TEXT NOT NULL,
    HORARIO TEXT,
    TIEMPO_ESTIMADO_ESPERA TEXT
);

-- TABLA DE LAS PARADAS
CREATE TABLE PARADAS (
    ID_PARADA INTEGER PRIMARY KEY,
    NOMBRE TEXT NOT NULL,
    LATITUD REAL NOT NULL,
    LONGITUD REAL NOT NULL
);

-- TABLA DE LOS RECORRIDOS
CREATE TABLE RECORRIDO (
    ID_RUTA INTEGER NOT NULL,
    ID_PARADA INTEGER NOT NULL,
    PRIMARY KEY (ID_RUTA, ID_PARADA),
    FOREIGN KEY (ID_RUTA) REFERENCES RUTA(ID_RUTA),
    FOREIGN KEY (ID_PARADA) REFERENCES PARADAS(ID_PARADA)
);